import sagemaker
from sagemaker.sklearn.model import SKLearnModel

# Get the SageMaker execution role (ensure this is running in an environment with the proper permissions)
role = sagemaker.get_execution_role()

# S3 path to your model artifact generated by the training job
# Example: "s3://your-bucket/SageMaker/your-training-job/model.tar.gz"
model_artifact = "s3://your-bucket/path/to/model.tar.gz"

# Create a SageMaker SKLearnModel object
sklearn_model = SKLearnModel(
    model_data=model_artifact,
    role=role,
    entry_point="inference.py",  # Your inference script (if needed)
    framework_version="0.23-1"
)

# Deploy the model to a SageMaker endpoint
predictor = sklearn_model.deploy(
    initial_instance_count=1,
    instance_type="ml.t2.medium"
)

# Example usage: make a prediction using the deployed endpoint
sample_input = [[0.5, 0.2, 0.8]]  # Replace with your feature values
prediction = predictor.predict(sample_input)
print("Prediction:", prediction)

# (Optional) Clean up by deleting the endpoint after testing:
# predictor.delete_endpoint()
